In [1]:
import torch
import torch.nn.functional as F
import numpy as np

# Generate a sample from a vector

In torch.multinomial vector passed to function becomes weight, it get proportional probability of being selected. Function returns indexes not values.

In [23]:
# a vector (must be tensor)
vect = torch.tensor([1,2,5], dtype = torch.float)

# sample a number (?)
torch.multinomial(vect,1)

tensor([2])

In [24]:
vect[torch.multinomial(vect,10,replacement=True)]

tensor([5., 5., 5., 1., 1., 5., 5., 5., 1., 5.])

In [25]:
# 10k samples!
mn = torch.multinomial(vect, 1000, replacement = True)

# collect the distribution
vals, counts = np.unique(mn, return_counts = True)

# print the output values and how often they occured
for v, c in zip(vals, counts):
  print(f'"{v}" was sampled {c} times ({c*100/len(mn):.2f}%)')

"0" was sampled 148 times (14.80%)
"1" was sampled 251 times (25.10%)
"2" was sampled 601 times (60.10%)


# With Softmaxification

In [35]:
# softmax the vector
vect_softmax = F.softmax(vect, dim = -1)

# new reporting
for v,c,vect_val in zip(vals, counts, vect_softmax):

  observed_frequency = c*100/len(mn)

  print(f'"{v}" was sampled {c:4} times. That is {observed_frequency:5.2f}%, and the softmax probability is {100*vect_val:.2f}%')

"0" was sampled  148 times. That is 14.80%, and the softmax probability is 1.71%
"1" was sampled  251 times. That is 25.10%, and the softmax probability is 4.66%
"2" was sampled  601 times. That is 60.10%, and the softmax probability is 93.62%


In [37]:
# now sampling from the softmax vector
mn = torch.multinomial(vect_softmax, 1000, replacement = True)
vals, counts = np.unique(mn, return_counts = True)

# new reporting
for v,c,vect_val in zip(vals, counts, vect_softmax):

  observed_frequency = c*100/len(mn)

  print(f'"{v}" was sampled {c:4} times. That is {observed_frequency:5.2f}%, and the softmax probability is {100*vect_val:.2f}%')

"0" was sampled   18 times. That is  1.80%, and the softmax probability is 1.71%
"1" was sampled   37 times. That is  3.70%, and the softmax probability is 4.66%
"2" was sampled  945 times. That is 94.50%, and the softmax probability is 93.62%


# Comparison with numpy.random.choice

In [38]:
np.random.choice(vect, 10)

array([2., 2., 1., 1., 2., 2., 1., 5., 2., 2.], dtype=float32)

In [42]:
# sample lots of values
mn = np.random.choice(vect, 10000, replace = True)
# report the results
vals, counts = np.unique(mn, return_counts = True)
for v,c,vectval in zip(vals, counts, vect):

  observed_frequency = c*100/len(mn)
  expected_frequency = 1*100/len(vect)

  print(f'"{v}" was sampled {c} times. that is {observed_frequency:.2f}%, and the expected probability is {expected_frequency:.2f}%')

"1.0" was sampled 3323 times. that is 33.23%, and the expected probability is 33.33%
"2.0" was sampled 3346 times. that is 33.46%, and the expected probability is 33.33%
"5.0" was sampled 3331 times. that is 33.31%, and the expected probability is 33.33%


In [44]:
# getting np.random.choce to match multinomial's function

# define probabilities (weights for selection)
prob_values = vect / sum(vect)

# sample lots of values
mn = np.random.choice(vect, 10000, replace = True, p = prob_values)

# rreport the results
vals, counts = np.unique(mn, return_counts = True)
for v,c,p in zip(vals, counts, prob_values):

  observed_frequency = c* 100 / len(mn)
  expected_frequency = p*100

  print(f'"{v}" was sampled {c} times. that is {observed_frequency:.2f}%, and the expected probability is {expected_frequency:.2f}%')

"1.0" was sampled 1220 times. that is 12.20%, and the expected probability is 12.50%
"2.0" was sampled 2557 times. that is 25.57%, and the expected probability is 25.00%
"5.0" was sampled 6223 times. that is 62.23%, and the expected probability is 62.50%
